// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnH_2EzovRMtccfNo2BDyeXluKXP7z4ic',
    appId: '1:89703840067:web:43dc4659c2f614937d57f6',
    messagingSenderId: '89703840067',
    projectId: 'cw-8-c1d68',
    authDomain: 'cw-8-c1d68.firebaseapp.com',
    storageBucket: 'cw-8-c1d68.firebasestorage.app',
    measurementId: 'G-SJ82WQ5555',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEkwiCxlt2utp75YP2XqSSZsGiypMUt8Q',
    appId: '1:89703840067:android:e1d9d62caa0a39747d57f6',
    messagingSenderId: '89703840067',
    projectId: 'cw-8-c1d68',
    storageBucket: 'cw-8-c1d68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaELOBdf0A79mKtQ2ihgupEgkY4gRvThw',
    appId: '1:89703840067:ios:11eebd82838308c37d57f6',
    messagingSenderId: '89703840067',
    projectId: 'cw-8-c1d68',
    storageBucket: 'cw-8-c1d68.firebasestorage.app',
    iosBundleId: 'com.example.imageLabeling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaELOBdf0A79mKtQ2ihgupEgkY4gRvThw',
    appId: '1:89703840067:ios:11eebd82838308c37d57f6',
    messagingSenderId: '89703840067',
    projectId: 'cw-8-c1d68',
    storageBucket: 'cw-8-c1d68.firebasestorage.app',
    iosBundleId: 'com.example.imageLabeling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnH_2EzovRMtccfNo2BDyeXluKXP7z4ic',
    appId: '1:89703840067:web:0ef6c1819cbbc3da7d57f6',
    messagingSenderId: '89703840067',
    projectId: 'cw-8-c1d68',
    authDomain: 'cw-8-c1d68.firebaseapp.com',
    storageBucket: 'cw-8-c1d68.firebasestorage.app',
    measurementId: 'G-R0Q9GYVDS2',
  );
}
